# /swagger/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts NodeJS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Contacts NodeJS
tags:
  - name: auth
    description: Operations related to authentication
paths:
  /auth/register:
    $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/send-reset-email:
    $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    $ref: '../swagger/paths/auth/reset-pwd.yaml'
components:
  responses:
    $ref: '../swagger/components/responses.yaml'
  schemas:
    $ref: '../swagger/components/schemas.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
