openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts NodeJS
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    Contacts NodeJS
tags:
  - name: contacts
  description: Operations related to contacts
servers:
  - url: <http://localhost:3000>
  - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    $ref: './swagger/paths/contacts/{id}/get.yaml'
components:
  schemas:
    $ref: './swagger/components/schemas.yaml'
  responses: 
    $ref: './swagger/components/responses.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
