# /swagger/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts NodeJS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Contacts NodeJS
tags:
  - name: auth
    description: Operations related to authentication
  - name: contacts
    description: Operations related to contacts
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-ndz9.onrender.com
  /auth/register:
    $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/send-reset-email:
    $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  responses:
    $ref: '../swagger/components/responses.yaml'
  schemas:
    $ref: '../swagger/components/schemas.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
